#!/bin/bash

print_usage() {
  echo "Usage: $0 <path-to-running_slips_info.txt>"
  echo
  echo "Required:"
  echo "  <path-to-running_slips_info.txt>  Path to the running_slips_info.txt file generated by Slips"
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  print_usage
  exit 0
fi

if [[ $# -ne 1 ]]; then
  print_usage
  exit 1
fi

file="$1"

if [[ ! -f "$file" ]]; then
  echo "Error: file not found: $file"
  exit 1
fi

file="$(realpath "$file")"

cd kalipso || exit 1
echo "To close all unused redis servers, run slips with --killall"
# Declare a string array
declare -a open_redis_servers=()
declare -a ports=()

while IFS= read -r line # read file line by line
do
    # ignore line if it starts with # or has Date in it
    if [[ -z "${line// }" ]] || [[ ${line} =~ "Date" ]] || [[ ${line} =~ "#" ]]; then
     continue
    fi

    # set , as delimiter
    IFS=','
    read -ra splitted_line <<< "$line"   # line is read into an array as tokens separated by ,

    # add the used file to open_redis_servers array
    open_redis_servers[${#open_redis_servers[@]}]=${splitted_line[1]}
    # append the used port to  ports arr
    ports[${#ports[@]}]=${splitted_line[2]}
done < "$file"



if [[ ${#open_redis_servers[@]} -eq 0 ]]; then
  echo "You have 0 open redis-servers to use. Make sure you run slips first"
  exit 1
# if we have only 1 server open, use it
elif [[ ${#open_redis_servers[@]} -eq 1 ]]; then
  port_to_use=${ports[0]}
# if we have more than 1 open redis server in the arr, prompt which one to use
elif [[ ${#open_redis_servers[@]} -gt 0 ]]; then
    echo "You have ${#open_redis_servers[@]} open redis servers, Choose which one to use [1,2,3 etc..] "
    # ctr to print next to each server
    ctr=1
    for value in "${open_redis_servers[@]}"
        do
             echo "[$ctr] $value - port ${ports[ctr-1]}"
             let ctr=ctr+1
        done
    # the user will choose 1,2,3 etc
    read index
    if ! [[ "$index" =~ ^[0-9]+$ ]] || (( index < 1 || index > ${#ports[@]} )); then
        echo "Error: invalid selection '$index'. Choose a number between 1 and ${#ports[@]}."
        exit 1
    fi
    let index=index-1
    # get the pid in this index
    port_to_use=${ports[index]}
fi
# run kalipso
node kalipso -l 2000 -p ${port_to_use}
